name: SystemSw.Sharp
on:
  push:
    branches:
      - develop
      - test
      - master

jobs:
  tag:
    name: Create Release Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: 'master'
          pre_release_branches: 'develop,test'
          
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

  build_sys8_api:
    name: Build, test, and Publish System8 API
    runs-on: ubuntu-latest
    needs: [tag]
    
    steps:    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: 'Get Previous tag'
      id: previoustag
      uses: actions-ecosystem/action-get-latest-tag@v1
          
    - name: Restore dependencies
      run: dotnet restore ./System8/System8.Api/System8.Api.csproj
      
    - name: Build
      run: dotnet build --no-restore ./System8/System8.Api/System8.Api.csproj
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish API
      if: success()
      run: dotnet publish -c Release -o ./Release/System8/Api ./System8/System8.Api/System8.Api.csproj

    - name: Zip API
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: './system8-api-${{ github.sha }}.zip'
        path: './Release/System8/Api'
        
    - name: Upload API
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./system8-api-${{ github.sha }}.zip"
        allowUpdates: 'true'
        commit: ${{ github.sha }}
        omitBody: 'true'
        tag: ${{ steps.previoustag.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}

  build_sys8_ui:
    name: Build and Publish System8 UI
    runs-on: ubuntu-latest
    needs: [tag]

    steps:
    - name: Setup NPM
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: 'Get Previous tag'
      id: previoustag
      uses: actions-ecosystem/action-get-latest-tag@v1
    
    - name: Restore dependencies
      run: dotnet restore ./System8/System8.Ui/System8.Ui.csproj
      
    - name: Build
      run: dotnet build --no-restore ./System8/System8.Ui/System8.Ui.csproj
      
    - name: Publish UI
      if: success()
      run: dotnet publish -c Release -o ./Release/System8/Ui ./System8/System8.Ui/System8.Ui.csproj
    
    - name: Zip UI
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: './system8-ui-${{ github.sha }}.zip'
        path: './Release/System8/Ui'
        
    - name: Upload UI
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./system8-ui-${{ github.sha }}.zip"
        allowUpdates: 'true'
        commit: ${{ github.sha }}
        tag: ${{ steps.previoustag.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}

  build_crosspoint_api:
    name: Build, test, and Publish Crosspoint API
    runs-on: ubuntu-latest
    needs: [tag]
    
    steps:    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: 'Get Previous tag'
      id: previoustag
      uses: actions-ecosystem/action-get-latest-tag@v1
          
    - name: Restore dependencies
      run: dotnet restore ./Crosspoint/Crosspoint.Api/Crosspoint.Api.csproj
      
    - name: Build
      run: dotnet build --no-restore ./Crosspoint/Crosspoint.Api/Crosspoint.Api.csproj
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish API
      if: success()
      run: dotnet publish -c Release -o ./Release/Crosspoint/Api ./Crosspoint/Crosspoint.Api/Crosspoint.Api.csproj

    - name: Zip API
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: './crosspoint-api-${{ github.sha }}.zip'
        path: './Release/Crosspoint/Api'
        
    - name: Upload API
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./crosspoint-api-${{ github.sha }}.zip"
        allowUpdates: 'true'
        commit: ${{ github.sha }}
        omitBody: 'true'
        tag: ${{ steps.previoustag.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}

  build_crosspoint_ui:
    name: Build and Publish Crosspoint UI
    runs-on: ubuntu-latest
    needs: [tag]

    steps:
    - name: Setup NPM
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: 'Get Previous tag'
      id: previoustag
      uses: actions-ecosystem/action-get-latest-tag@v1
    
    - name: Restore dependencies
      run: dotnet restore ./Crosspoint/Crosspoint.Ui/Crosspoint.Ui.csproj
      
    - name: Build
      run: dotnet build --no-restore ./Crosspoint/Crosspoint.Ui/Crosspoint.Ui.csproj
      
    - name: Publish UI
      if: success()
      run: dotnet publish -c Release -o ./Release/Crosspoint/Ui ./Crosspoint/Crosspoint.Ui/Crosspoint.Ui.csproj
    
    - name: Zip UI
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: './crosspoint-ui-${{ github.sha }}.zip'
        path: './Release/Crosspoint/Ui'
        
    - name: Upload UI
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./crosspoint-ui-${{ github.sha }}.zip"
        allowUpdates: 'true'
        commit: ${{ github.sha }}
        tag: ${{ steps.previoustag.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
