name: .NET 5.0 Build and Tag

on:
  push:
    branches: [ develop, test ]
  pull_request:
    branches: [ master ]

jobs:
  generate_build:
    name: Generate Appropriate Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Versioning
        id: version
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: 'develop,test,master'
          PRERELEASE_SUFFIX: 'pre-'
          INITIAL_VERSION: '1.0.0'

  build_api:
    name: Build, test, and Publish API
    runs-on: ubuntu-latest
    needs: [generate_build]
    
    steps:    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Restore dependencies
      run: dotnet restore ./SystemSw-Api/SystemSw-Api.csproj
      
    - name: Build
      run: dotnet build --no-restore ./SystemSw-Api/SystemSw-Api.csproj
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish API
      if: success()
      run: dotnet publish -c Release -o ./Release-Api ./SystemSw-Api/SystemSw-Api.csproj

    - name: Zip API
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: './release-api-${{ github.sha }}.zip'
        path: './Release-Api'
        
    - name: Upload API
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./release-api-${{ github.sha }}.zip"
        commit: ${{ github.sha }}
        omitBody: 'true'
        tag: 'latest'
        token: ${{ secrets.GITHUB_TOKEN }}

  build_ui:
    name: Build and Publish UI
    runs-on: ubuntu-latest
    needs: [generate_build]

    steps:
    - name: Setup NPM
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Restore dependencies
      run: dotnet restore ./SystemSw-UI/SystemSw-UI.csproj
      
    - name: Build
      run: dotnet build --no-restore ./SystemSw-UI/SystemSw-UI.csproj
      
    - name: Publish UI
      if: success()
      run: dotnet publish -c Release -o ./Release-UI ./SystemSw-UI/SystemSw-UI.csproj
    
    - name: Zip UI
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: './release-ui-${{ github.sha }}.zip'
        path: './Release-UI'
        
    - name: Upload UI
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./release-ui-${{ github.sha }}.zip"
        commit: ${{ github.sha }}
        tag: 'latest'
        token: ${{ secrets.GITHUB_TOKEN }}
