name: Automatic Tag Creation

on:
  push:
    branches: [ develop, test ]
  pull_request:
    branches: [ master ]

jobs:
  generate_build:
    name: Generate Appropriate Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Versioning
        id: version
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: 'master'
          PRERELEASE_SUFFIX: 'pre-'
          INITIAL_VERSION: '1.0.0'
